### ISSUE TITLE
[誤植報告] p55 chapter2.3 アルゴリズム2.2

### ISSUE THREAD

**Issue by speed1313** [joisino/gnnbook#1]
楽しく読ませていただいております. 誤植を見つけたので報告します.

第一刷p55 chapter2.3 アルゴリズム2.2のstep 2の
$$Z = [\sqrt{\lambda_1}v_1, ..,\sqrt{\lambda_d}v_d]^T$$
の転置(^T)が不要だと思いました.
$Z$は $ n*d $ 行列で, 転置を取る前にすでに $ n* d $ になっているためです.

ご確認お願いいたします.

**Comment by joisino** [comment]
ご指摘ありがとうございます。指摘は正しいです。 #2 で対応いたしました。ありがとうございました。
