### ISSUE TITLE
[誤植?報告] p82 同類・異類選好グラフ畳み込みネットワーク

### ISSUE THREAD

**Issue by 1taroh** [joisino/gnnbook#3]
大変興味深い本を著述いただき，ありがとうございます．

p82 の 20-22 行目の
「第一に，同類・異類選好グラフ畳み込みネットワークは単純グラフ畳み込みと同様に，パラメータの存在しない埋め込みモデルです」
とありますが， p79 における単純グラフ畳み込みの説明では，式 (3.23) にあるように学習パラメータ $\boldsymbol{W}$ があります．
「パラメータの存在しない埋め込みモデル」ではなく，「活性化関数の存在しない埋め込みモデル」でしょうか？

ご確認いただけると幸いです．

**Comment by joisino** [comment]
ご指摘ありがとうございます。

単純グラフ畳み込みの W は埋め込みのパラメータと見ることもできる一方、後段の分類モデルのパラメータと見ることもできます。どこまでを埋め込み、どこからが分類モデルだとみなすかには自由度があります。
頂点分類問題に用いる場合は $W \in \mathbb{R}^{d \times |Y|}$ であり、 $X' = \hat{A}^L X$ を埋め込み、 $\text{softmax}(X' W)$ を（線形）分類モデルとみなすことが多いです。
その意味で単純グラフ畳み込みが「パラメータの存在しない埋め込みモデル」であると表記しました。
少し分かりづらいですがうまい修正の方法が思いつかなかったので、一旦修正なしといたします。
