### ISSUE TITLE
[誤植報告]初版p75 式(3.8)

### ISSUE THREAD

**Issue by speed1313** [joisino/gnnbook#4]
初版p75 式(3.8) について$\sigma(\hat{A}H^{l}W^{l+1}$の$W^{l+1}$は行列のshapeを合わせるために転置されている必要があるのではないかと思ったのですが、あっておりますでしょうか？

**Comment by joisino** [comment]
ご指摘は正しいです。 #6 で対応いたしました。ご報告ありがとうございました。
