### ISSUE TITLE
[質問] 初版p72 通常のニューラルネットワークはGNNの特殊例　について

### ISSUE THREAD

**Issue by speed1313** [joisino/gnnbook#5]
p72において通常のニューラルネットワークをGNNの集約しないバージョンとしてGNNの特殊例と見做せるという記述がありますが、通常のニューラルネットワークをGNNとしてみた時のノードとデータの対応関係がよくわかりません。

各ノードの埋め込みは画像$\bold{x}_i$で初期化され、それぞれのノードが独立して通常のニューラルネットワークの変換がかけられるという理解であってますでしょうか？
その場合グラフのノード数は一つありさえすれば本来は良いという理解であっていますか？

そこからさらにGNNとしてメッセージパッシングする場合は画像データセットのいくつかの画像をノードとして設定してメッセージパッシングしていくのでしょうか？

**Comment by joisino** [comment]
> 各ノードの埋め込みは画像$\bold{x}_i$で初期化され、それぞれのノードが独立して通常のニューラルネットワークの変換がかけられるという理解であってますでしょうか？

はい、正しいです。

> その場合グラフのノード数は一つありさえすれば本来は良いという理解であっていますか？

ノード数は画像の個数個必要です。それぞれのノードの特徴量は異なる（異なる画像である）ので、別のノードとして扱う必要があります。

> そこからさらにGNNとしてメッセージパッシングする場合は画像データセットのいくつかの画像をノードとして設定してメッセージパッシングしていくのでしょうか？

そうです。同じユーザーが投稿した画像どうしを辺で繋ぐ（同じユーザーが投稿した画像どうしは同じラベルである可能性が高いため）、撮影された地点が近い画像どうしを辺で繋ぐなどしたグラフにグラフニューラルネットワークを適用することが考えられます。


文書分類（例 3.1）が典型的な例です。
通常のニューラルネットワークは文書の情報 (bag of words ベクトル）を受け取り、文書のカテゴリを文書ごと独立に予測します。
グラフニューラルネットワークは当該文書だけでなく、周辺の文書の情報も使って文書のカテゴリを予測します。
例 3.1 の 2 層グラフ畳み込みニューラルネットワーク 式 (3.38) において、辺が存在しない (A = 単位行列) の場合、これは 2 層の多層パーセプトロン（= 通常のニューラルネットワーク）となります。

**Comment by speed1313** [comment]
ありがとうございます
