### ISSUE TITLE
誤植について

### ISSUE THREAD

**Issue by nagas1226** [joisino/gnnbook#7]
はじめまして．『グラフニューラルネットワーク』の第3刷について，以下2点ご確認していただけますでしょうか．
- 式(2.37)の左辺はWではなくD+Wではないでしょうか．
- p.192の式(6.95)の直後の本文において，(\theta_1, \theta_2)ではなく，(\theta_0, \theta_1)ではなくではないでしょうか．

よろしくお願いします．

**Comment by joisino** [comment]
ご指摘ありがとうございます。いずれもご指摘は正しいです。 #8 で対応しました。
