### ISSUE TITLE
誤植報告: p.46, (2.28)

### ISSUE THREAD

**Issue by tatsuookubo** [joisino/gnnbook#9]
導出が丁寧に書かれた素晴らしい本をどうも有難うございます。

議論の本質に関係ありませんが、ベクトルのサイズについて気付いた点がありましたので、お知らせします（第１刷）。

- p.46 (2.28) 右辺の０はスカラーではなくV _U次元のゼロベクトル
- p.48 (2.31)の直前：qの次元はnもしくはV_U?
- p.51 下から８行目：B_vは疎な行列　→ 疎なベクトル 

以上にて失礼します。

**Comment by joisino** [comment]
ご報告ありがとうございます。ご指摘は全て正しいです。#10 にて対応しました。
